### ISSUE TITLE
LÖVR master branch does not compile

### ISSUE THREAD

**Issue by appgurueu** [bjornbytes/lovr#275]
LÖVR master branch does not compile on Ubuntu 20.04

Errors:
```
lovr/src/core/os_linux.c:57:17: error: dereferencing pointer to incomplete type ‘struct passwd’
   57 |     path = entry->pw_dir;
      |                 ^~
```
and
```
lovr/src/core/os_linux.c:100:3: error: unknown type name ‘ssize_t’; did you mean ‘size_t’?
  100 |   ssize_t length = readlink("/proc/self/exe", buffer, size - 1);
      |   ^~~~~~~
      |   size_t
```
